### ISSUE TITLE
docker install check not adequate

### ISSUE THREAD

**Issue by hshuaib90** [GSTT-CSC/MLOps#10]
In the README, checking docker is working by typing the command:
`docker --help`
 is not enough as this can return correctly even if the docker server is not up and running.

Probably better to use something like:
`docker images ls`

**Comment by laurencejackson** [comment]
I think there's some confusion here sorry, the `docker --help` command is just to check that docker is installed on the local machine. You're right though there is no post-installation check to ensure the server is running. 

@tapjason can you create a step 3 in the getting started installation guide describing how to ensure the server is running. Either with `docker ps` or with a  screenshot of the expected terminal output went he containers start successfully.
