### ISSUE TITLE
building 'web' in docker-compose took 8 minutes

### ISSUE THREAD

**Issue by hshuaib90** [GSTT-CSC/MLOps#11]
Is there a reason why it takes so long? Looking at the mlflow/Dockerfile it is pretty simple to build. May be worth putting in a warning in the README that i might take sometime first time 

I did this locally on:
<img width="245" alt="image" src="https://user-images.githubusercontent.com/19840489/120903327-78fbba80-c63d-11eb-8ea6-ab849e9ead74.png">

**Comment by tapjason** [comment]
The README mentions that "docker images that are not present on your local system will be pulled from dockerhub (which might take a while)", however, I'm not sure which part of the build report these images would be from. It seems that the parts taking the longest time to build are part of the docker python3.8 library, although I'm not sure how relevant that is. 
<img width="572" alt="Screen Shot 2021-07-07 at 3 58 36 PM" src="https://user-images.githubusercontent.com/13169388/124782520-3549e880-df3c-11eb-88cc-15985eee3d24.png">

**Comment by laurencejackson** [comment]
Thanks Jason, this is interesting. It might be that we could get away with a lightweight python image as opposed to the main image. When `docker-compose` builds 'web' it is building the Dockerfile at MLOPs/mlflow_server/mlflow/Dockerfile. 

Could you try changing the python:3.8 image there to a lightweight python3.8 image? e.g. `FROM python:3.8-slim`

Once you've tried that could you rebuild and paste the same screenshot as you put here. Remember to delete your local cached Docker images or rebuild without cached images. Let me know if you encounter any errors or warnings with this approach.

**Comment by tapjason** [comment]
After changing to the lightweight python3.8 image, the package installation for python3.8 becomes much faster than before, however I get an extremely long error log for the psycopg2 package installation that would be too long to attach here, however it seems to center around a pg_config executable being unable to be located.

<img width="388" alt="Screen Shot 2021-07-08 at 3 26 34 PM" src="https://user-images.githubusercontent.com/13169388/124939329-eb770600-e000-11eb-8c2c-340424b83deb.png">

I added a line to install libpq-dev which contains the pg_config executable, and from there I reached the error shown below. Is there any pathing necessary to be added or am I making some fundamental mistake?

<img width="565" alt="Screen Shot 2021-07-08 at 3 25 54 PM" src="https://user-images.githubusercontent.com/13169388/124939338-edd96000-e000-11eb-8a18-cf7cc3626bd8.png">

**Comment by laurencejackson** [comment]
Thanks Jason, this looks promising - could you try updating apt-get before you install libpq-dev?

`RUN apt-get update && apt-get -y install libpq-dev`

(The && chains together two commands in sequence and the -y flag prevents errors when apt-get asks for user confirmation)

**Comment by tapjason** [comment]
I added your line in place of what I had for installing libpq-dev, and I got the following error. 
<img width="1046" alt="Screen Shot 2021-07-08 at 8 54 10 PM" src="https://user-images.githubusercontent.com/13169388/124982651-dc0eb180-e02e-11eb-92ad-e11ee517cf0e.png">


The error specifies a missing gcc compiler package and recommends installing psycopg2-binary, however I can't install with the typical line "apt-get -y install psycopg2-binary without running into a similar error from above "Unable to locate package psycopg2-binary". 

I resorted to installing the gcc package directly with the dockerfile as follows:
<img width="499" alt="Screen Shot 2021-07-08 at 9 05 13 PM" src="https://user-images.githubusercontent.com/13169388/124983725-3c522300-e030-11eb-8444-397fbf4cb01a.png">

This built 'web' successfully, taking 4~ minutes compared to the 10~ minutes it took locally before, however this should vary between different machines. The gcc package installation took 1 minute, so it might be worth looking into how to reduce unnecessary packages within this further as well as the 'nginx' build.

**Comment by laurencejackson** [comment]
Amazing, thanks Jason - I would say that a 6 minute reduction is good progress and sufficient to close this ticket. If we decide that the other docker-compose services (e.g. nginx) are taking too long we can raise other issues address them later.

To reduce the number of layers you can simply write: `RUN apt-get update && apt-get -y install libpq-dev gcc` to install libpq-dev and gcc in the same command. 

Please could you raise a pull request to merge your branch into the develop branch and we can review and merge.
