### ISSUE TITLE
Acknowledgements/Citations

### ISSUE THREAD

**Issue by hshuaib90** [GSTT-CSC/MLOps#20]
Can we add a note to the README for how others can appropriately acknowledge or cite this work?

**Comment by laurencejackson** [comment]
IEEE Reference List Format seems appropriate, at least until (if) superceded by a publication: 

AuthorLast, I (Year) Title of Code (Version #.#) [Source code]. URL.

Example: Facebook (2020) Recoil [Source code]. https://github.com/facebookexperimental/Recoil.
